
# LOGS - (บ่นไปเรื่อย)

# Year Month Date
# (2026-8-6)
# ผมคิดว่าอยากที่ทำให้โปรเจคมันเป็นรูปร่างคร่าวๆก่อน
#  ถึงแม้จะตัวไอเดียโปรเจคยังไม่เคลียร์
#  	เพื่อให้ไม่เป็นการเสียเวลาเปล่า
# Makefile + Bash scripting + docker compose น่าจะเพียงการ build project ขึ้นมา


########################################################################
########################################################################
########################################################################



# all the project required directories
SRC_DIR = ./src
TEMP_DIR = ./temp
HELPER_SCRIPT_DIR = ${SRC_DIR}/helper_script


# the name of this project
NAME = transcendence

# stamp files - convention to let makefile know
#									by creating stamp file for each operation


all: ${name}

${name}:


${TEMP_DIR}:
	mkdir -p $@


.PHONY: all clean fclean re purge nuke ${name}
