FROM postgres:alpine

# USER root

# RUN mkdir -p /app
# RUN apk update && apk add --no-cache sed grep shadow su-exec

# COPY ./entrypoint.sh /app/entrypoint.sh
# RUN chmod +x /app/entrypoint.sh

# ENTRYPOINT ["/app/entrypoint.sh"]
# CMD ["postgres"]

