/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf -o model.tsx -t 
Author: MMSkecthfab (https://sketchfab.com/MMDSKETCH)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/inugami-korone-79ac8befcfb94ac8a0b1bf546052ab69
Title: Inugami Korone
*/

import * as THREE from 'three'
import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'

type GLTFAction = THREE.AnimationAction;

type GLTFResult = GLTF & {
  nodes: {
    Object_402: THREE.SkinnedMesh
    Object_403: THREE.SkinnedMesh
    Object_404: THREE.SkinnedMesh
    Object_405: THREE.SkinnedMesh
    Object_406: THREE.SkinnedMesh
    Object_407: THREE.SkinnedMesh
    Object_408: THREE.SkinnedMesh
    Object_409: THREE.SkinnedMesh
    Object_410: THREE.SkinnedMesh
    Object_411: THREE.SkinnedMesh
    Object_412: THREE.SkinnedMesh
    Object_413: THREE.SkinnedMesh
    Object_414: THREE.SkinnedMesh
    Object_415: THREE.SkinnedMesh
    Object_416: THREE.SkinnedMesh
    Object_417: THREE.SkinnedMesh
    Object_418: THREE.SkinnedMesh
    Object_419: THREE.SkinnedMesh
    Object_420: THREE.SkinnedMesh
    Object_421: THREE.SkinnedMesh
    Object_422: THREE.SkinnedMesh
    Object_423: THREE.SkinnedMesh
    Object_424: THREE.SkinnedMesh
    Object_425: THREE.SkinnedMesh
    Object_426: THREE.SkinnedMesh
    Object_427: THREE.SkinnedMesh
    Object_428: THREE.SkinnedMesh
    Object_429: THREE.SkinnedMesh
    Object_430: THREE.SkinnedMesh
    Object_431: THREE.SkinnedMesh
    Object_432: THREE.SkinnedMesh
    Object_433: THREE.SkinnedMesh
    Object_434: THREE.SkinnedMesh
    Object_435: THREE.SkinnedMesh
    Object_436: THREE.SkinnedMesh
    Object_437: THREE.SkinnedMesh
    Object_438: THREE.SkinnedMesh
    Object_439: THREE.SkinnedMesh
    Object_440: THREE.SkinnedMesh
    Object_441: THREE.SkinnedMesh
    Object_442: THREE.SkinnedMesh
    Object_443: THREE.SkinnedMesh
    Object_444: THREE.SkinnedMesh
    Object_445: THREE.SkinnedMesh
    Object_446: THREE.SkinnedMesh
    Object_447: THREE.SkinnedMesh
    _rootJoint: THREE.Bone
  }
  materials: {
    material: THREE.MeshBasicMaterial
    material_1: THREE.MeshBasicMaterial
    material_2: THREE.MeshBasicMaterial
    material_3: THREE.MeshBasicMaterial
    material_4: THREE.MeshBasicMaterial
    material_5: THREE.MeshBasicMaterial
    material_6: THREE.MeshBasicMaterial
    material_7: THREE.MeshBasicMaterial
    material_8: THREE.MeshBasicMaterial
    material_9: THREE.MeshBasicMaterial
    material_10: THREE.MeshBasicMaterial
    material_11: THREE.MeshBasicMaterial
    material_12: THREE.MeshBasicMaterial
    material_13: THREE.MeshBasicMaterial
    material_14: THREE.MeshBasicMaterial
    material_15: THREE.MeshBasicMaterial
    material_16: THREE.MeshBasicMaterial
    material_17: THREE.MeshBasicMaterial
    material_18: THREE.MeshBasicMaterial
    material_19: THREE.MeshBasicMaterial
    material_20: THREE.MeshBasicMaterial
    material_21: THREE.MeshBasicMaterial
    material_22: THREE.MeshBasicMaterial
    material_23: THREE.MeshBasicMaterial
    material_24: THREE.MeshBasicMaterial
    material_25: THREE.MeshBasicMaterial
    material_26: THREE.MeshBasicMaterial
    material_27: THREE.MeshBasicMaterial
    material_28: THREE.MeshBasicMaterial
    material_29: THREE.MeshBasicMaterial
    material_30: THREE.MeshBasicMaterial
    material_31: THREE.MeshBasicMaterial
    material_32: THREE.MeshBasicMaterial
    material_33: THREE.MeshBasicMaterial
    material_34: THREE.MeshBasicMaterial
    material_35: THREE.MeshBasicMaterial
    material_36: THREE.MeshBasicMaterial
    material_37: THREE.MeshBasicMaterial
    material_38: THREE.MeshBasicMaterial
    material_39: THREE.MeshBasicMaterial
    material_40: THREE.MeshBasicMaterial
    material_41: THREE.MeshBasicMaterial
    material_42: THREE.MeshBasicMaterial
    material_43: THREE.MeshBasicMaterial
    material_44: THREE.MeshBasicMaterial
    OH_Outline_Material: THREE.MeshBasicMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: React.JSX.IntrinsicElements['group']) {
  const { scene } = useGLTF('/3d-assets/korone/scene.gltf')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <primitive object={nodes._rootJoint} />
          <skinnedMesh geometry={nodes.Object_402.geometry} material={materials.material} skeleton={nodes.Object_402.skeleton} />
          <skinnedMesh geometry={nodes.Object_403.geometry} material={materials.material_1} skeleton={nodes.Object_403.skeleton} />
          <skinnedMesh geometry={nodes.Object_404.geometry} material={materials.material_2} skeleton={nodes.Object_404.skeleton} />
          <skinnedMesh geometry={nodes.Object_405.geometry} material={materials.material_3} skeleton={nodes.Object_405.skeleton} />
          <skinnedMesh geometry={nodes.Object_406.geometry} material={materials.material_4} skeleton={nodes.Object_406.skeleton} />
          <skinnedMesh geometry={nodes.Object_407.geometry} material={materials.material_5} skeleton={nodes.Object_407.skeleton} />
          <skinnedMesh geometry={nodes.Object_408.geometry} material={materials.material_6} skeleton={nodes.Object_408.skeleton} />
          <skinnedMesh geometry={nodes.Object_409.geometry} material={materials.material_7} skeleton={nodes.Object_409.skeleton} />
          <skinnedMesh geometry={nodes.Object_410.geometry} material={materials.material_8} skeleton={nodes.Object_410.skeleton} />
          <skinnedMesh geometry={nodes.Object_411.geometry} material={materials.material_9} skeleton={nodes.Object_411.skeleton} />
          <skinnedMesh geometry={nodes.Object_412.geometry} material={materials.material_10} skeleton={nodes.Object_412.skeleton} />
          <skinnedMesh geometry={nodes.Object_413.geometry} material={materials.material_11} skeleton={nodes.Object_413.skeleton} />
          <skinnedMesh geometry={nodes.Object_414.geometry} material={materials.material_12} skeleton={nodes.Object_414.skeleton} />
          <skinnedMesh geometry={nodes.Object_415.geometry} material={materials.material_13} skeleton={nodes.Object_415.skeleton} />
          <skinnedMesh geometry={nodes.Object_416.geometry} material={materials.material_14} skeleton={nodes.Object_416.skeleton} />
          <skinnedMesh geometry={nodes.Object_417.geometry} material={materials.material_15} skeleton={nodes.Object_417.skeleton} />
          <skinnedMesh geometry={nodes.Object_418.geometry} material={materials.material_16} skeleton={nodes.Object_418.skeleton} />
          <skinnedMesh geometry={nodes.Object_419.geometry} material={materials.material_17} skeleton={nodes.Object_419.skeleton} />
          <skinnedMesh geometry={nodes.Object_420.geometry} material={materials.material_18} skeleton={nodes.Object_420.skeleton} />
          <skinnedMesh geometry={nodes.Object_421.geometry} material={materials.material_19} skeleton={nodes.Object_421.skeleton} />
          <skinnedMesh geometry={nodes.Object_422.geometry} material={materials.material_20} skeleton={nodes.Object_422.skeleton} />
          <skinnedMesh geometry={nodes.Object_423.geometry} material={materials.material_21} skeleton={nodes.Object_423.skeleton} />
          <skinnedMesh geometry={nodes.Object_424.geometry} material={materials.material_22} skeleton={nodes.Object_424.skeleton} />
          <skinnedMesh geometry={nodes.Object_425.geometry} material={materials.material_23} skeleton={nodes.Object_425.skeleton} />
          <skinnedMesh geometry={nodes.Object_426.geometry} material={materials.material_24} skeleton={nodes.Object_426.skeleton} />
          <skinnedMesh geometry={nodes.Object_427.geometry} material={materials.material_25} skeleton={nodes.Object_427.skeleton} />
          <skinnedMesh geometry={nodes.Object_428.geometry} material={materials.material_26} skeleton={nodes.Object_428.skeleton} />
          <skinnedMesh geometry={nodes.Object_429.geometry} material={materials.material_27} skeleton={nodes.Object_429.skeleton} />
          <skinnedMesh geometry={nodes.Object_430.geometry} material={materials.material_28} skeleton={nodes.Object_430.skeleton} />
          <skinnedMesh geometry={nodes.Object_431.geometry} material={materials.material_29} skeleton={nodes.Object_431.skeleton} />
          <skinnedMesh geometry={nodes.Object_432.geometry} material={materials.material_30} skeleton={nodes.Object_432.skeleton} />
          <skinnedMesh geometry={nodes.Object_433.geometry} material={materials.material_31} skeleton={nodes.Object_433.skeleton} />
          <skinnedMesh geometry={nodes.Object_434.geometry} material={materials.material_32} skeleton={nodes.Object_434.skeleton} />
          <skinnedMesh geometry={nodes.Object_435.geometry} material={materials.material_33} skeleton={nodes.Object_435.skeleton} />
          <skinnedMesh geometry={nodes.Object_436.geometry} material={materials.material_34} skeleton={nodes.Object_436.skeleton} />
          <skinnedMesh geometry={nodes.Object_437.geometry} material={materials.material_35} skeleton={nodes.Object_437.skeleton} />
          <skinnedMesh geometry={nodes.Object_438.geometry} material={materials.material_36} skeleton={nodes.Object_438.skeleton} />
          <skinnedMesh geometry={nodes.Object_439.geometry} material={materials.material_37} skeleton={nodes.Object_439.skeleton} />
          <skinnedMesh geometry={nodes.Object_440.geometry} material={materials.material_38} skeleton={nodes.Object_440.skeleton} />
          <skinnedMesh geometry={nodes.Object_441.geometry} material={materials.material_39} skeleton={nodes.Object_441.skeleton} />
          <skinnedMesh geometry={nodes.Object_442.geometry} material={materials.material_40} skeleton={nodes.Object_442.skeleton} />
          <skinnedMesh geometry={nodes.Object_443.geometry} material={materials.material_41} skeleton={nodes.Object_443.skeleton} />
          <skinnedMesh geometry={nodes.Object_444.geometry} material={materials.material_42} skeleton={nodes.Object_444.skeleton} />
          <skinnedMesh geometry={nodes.Object_445.geometry} material={materials.material_43} skeleton={nodes.Object_445.skeleton} />
          <skinnedMesh geometry={nodes.Object_446.geometry} material={materials.material_44} skeleton={nodes.Object_446.skeleton} />
          <skinnedMesh geometry={nodes.Object_447.geometry} material={materials.OH_Outline_Material} skeleton={nodes.Object_447.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/3d-assets/korone/scene.gltf')
