/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Basic Hello world test
         * @description the most basic simple get to the backend service
         */
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user account */
        post: operations["UserController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get user profile
         * @description Retrieves the authenticated user’s profile if no query params are passed. Provide either `id` or `tagId` to view another user’s profile. Providing both will return a 400 error.
         */
        get: operations["UserController_getProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/profile/uploadProfilePic": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload user profile picture */
        post: operations["UserController_uploadProfilePic"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * update the user profile
         * @description update the user profile
         */
        patch: operations["UserController_update"];
        trace?: never;
    };
    "/user/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete user from the database
         * @description takes access_token from Authorization: Bearer header     and allow only role ADMIN and EDITOR to delete user
         */
        delete: operations["UserController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/title/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * get all the titles available
         * @description receive an array of all titles       available in the database
         */
        get: operations["TitleController_getAllTitles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/title": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * get all the titles available for this current user / specific titles
         * @description receive an array of this user titles       available
         */
        get: operations["TitleController_getUserTitles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/title/find": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * find the title details
         * @description provide the query to get the detail of the       specific title by id or by name
         */
        get: operations["TitleController_findTitle"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/title/new": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * create new title to database
         * @description added new title to the website       NOTE: Only for ADMIN Role
         */
        post: operations["TitleController_createNewTitle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/title/give": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * giver user a title
         * @description ADMIN only
         */
        post: operations["TitleController_giveUserTitle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/title/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * revoke title from the user
         * @description ADMIN Only
         */
        delete: operations["TitleController_revokeUserTitle"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/title/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * update the title
         * @description update the target title id details
         */
        patch: operations["TitleController_updateTitle"];
        trace?: never;
    };
    "/title/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * delete a title
         * @description delele a sepecific title by title id. ADMIN ONLY
         */
        delete: operations["TitleController_deleteTitle"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuthController_authCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_registerUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * User Login
         * @description Accepts email and password, verifies credentials,     and returns a JWT.
         */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh JWT Token API
         * @description takes the refresh token from 'Authorization: Bearer refreshToken'     in the header of the request
         */
        post: operations["AuthController_refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/signout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke the jwt refresh token
         * @description take the access_token from Authoriazation: Bearer header     from the POST request and set the hashedRefeshToken in the user table to     NULL
         */
        post: operations["AuthController_signOut"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuthController_googleLogin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuthController_googleCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/42/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuthController_fortyTwoLogin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/42/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuthController_fortyTwoCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ChatController_getAllUserRoom"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/dm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ChatController_dmUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/message": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ChatController_getMessagesRoom"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/room/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ChatController_createChatRoom"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/room/invite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ChatController_inviteToChatRoom"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/room/leave": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ChatController_leaveTheChatRoom"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/room/kick": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ChatController_kickUserChatRoom"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/friend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["FriendController_getAllFriends"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/friend/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["FriendController_makeFriendRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/friend/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["FriendController_acceptFriendRequest"];
        trace?: never;
    };
    "/friend/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["FriendController_rejectFriendRequest"];
        trace?: never;
    };
    "/friend/block": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["FriendController_blockUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/game/lobby/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["LobbyController_createLobbyRoom"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/game/lobby/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["LobbyController_joinLobbyRoom"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/game/lobby/leave": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["LobbyController_leaveLobbyRoom"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/game/lobby/allRooms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["LobbyController_getAllLobbyRoom"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/game/lobby/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["LobbyController_updateGameSettings"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateUserDto: {
            /**
             * @description the email of the user
             * @example user@example.com
             */
            email: string;
            /**
             * @description the hashed password of the user
             * @example SecurePassword123
             */
            password: string;
            /**
             * @description the display name of the user
             * @example InwZa007
             */
            displayName?: string | null;
            /** @description The url to the profile image of the user */
            avatarUrl?: string | null;
        };
        UnauthorizedErrorDto: {
            /**
             * @description Http error status code
             * @example 401
             */
            statusCode: number;
            /** @example Unauthorized */
            message: string;
        };
        GetUserProfileDto: {
            /**
             * @description tag id of user
             * @example YYMMDD_0000
             */
            tagId: string;
            /**
             * @description the email of the user
             * @example user@example.com
             */
            email: string;
            /**
             * @description The role of the user
             * @example USER
             * @enum {string}
             */
            role: "ADMIN" | "EDITOR" | "USER";
            /**
             * @description the display name of the user
             * @example InwZa007
             */
            displayName: string | null;
            /** @description The url to the profile image of the user */
            avatarUrl: string | null;
            /**
             * Format: date-time
             * @description The time and date that this user was created
             */
            createdAt: string;
            /**
             * @description The pronoun of the user
             * @example they/them
             * @enum {string|null}
             */
            pronoun: "he/him" | "she/her" | "they/them" | "prefer not to say" | null;
            /**
             * @description signature is like something the user want to say in a form of small message in their profile
             * @example I'm popeye popsiam USA.
             */
            signature: string | null;
            /**
             * @description title user wants to show on their profile
             * @example God-Like win streaks
             */
            activeTitleId: string | null;
            /**
             * @description The card theme user will use
             * @example STANDARD
             * @enum {string}
             */
            cardTheme: "STANDARD" | "FANTASY";
            /**
             * @description The active title name that user use
             * @example Sheriff
             */
            titleName: string | null;
        };
        UpdateUserDto: {
            /**
             * @description the hashed password of the user
             * @example SecurePassword123
             */
            password?: string;
            /**
             * @description the display name of the user
             * @example InwZa007
             */
            displayName?: string | null;
            /** @description The url to the profile image of the user */
            avatarUrl?: string | null;
            /**
             * @description The pronoun of the user
             * @example they/them
             * @enum {string|null}
             */
            pronoun?: "he/him" | "she/her" | "they/them" | "prefer not to say" | null;
            /**
             * @description signature is like something the user want to say in a form of small message in their profile
             * @example I'm popeye popsiam USA.
             */
            signature?: string | null;
            /**
             * @description title user wants to show on their profile
             * @example God-Like win streaks
             */
            activeTitleId?: string | null;
            /**
             * @description The card theme user will use
             * @example STANDARD
             * @enum {string}
             */
            cardTheme?: "STANDARD" | "FANTASY";
        };
        TitleDto: {
            /**
             * @description The id of the title
             * @example xxxx_xxxx_xxxx
             */
            id: string;
            /**
             * @description the name of the title
             * @example all in one
             */
            name: string;
            /**
             * @description the description of the title
             * @example the person really likes to all in.
             */
            description: string | null;
            /**
             * Format: date-time
             * @description The time and date of when this title was added
             */
            createdAt: string;
        };
        GetUserTitleDto: {
            /**
             * @description the name of the title
             * @example all in one
             */
            name: string;
            /**
             * @description the description of the title
             * @example the person really likes to all in.
             */
            description: string | null;
            /** @description the title id */
            titleId: string;
            /**
             * Format: date-time
             * @description the date this user got the title
             */
            unlockedAt: string;
        };
        CreateNewTitleZodDto: {
            /** @description the name of the title to create */
            name: string;
            /** @description The description of the new title */
            description?: string | null;
            /**
             * Format: date-time
             * @description the Created time of the title. no need this is optional
             */
            createdAt?: string;
        };
        UserTitleDto: {
            /** @description the id of the user that own this title */
            userId: string;
            /** @description the title id */
            titleId: string;
            /**
             * Format: date-time
             * @description the date this user got the title
             */
            unlockedAt: string;
        };
        UpdateTitleZodDto: {
            /** @description the name of the title */
            name: string;
            /** @description The description of the title */
            description?: string | null;
            /**
             * Format: date-time
             * @description the Created time of the title. no need this is optional
             */
            createdAt?: string;
        };
        LoginDto: {
            /**
             * @description The email registered to the account
             * @example user@example.com
             */
            email: string;
            /**
             * @description The plain-text user password.
             * @example password123
             */
            password: string;
        };
        LoginSuccessResponseDto: {
            /**
             * @description The authenticated user ID
             * @example 1
             */
            id: number;
            /**
             * @description Signed JWT access token
             * @example lsd234k5j5234k5lj1kj2h3g4341k2313kl2j2h4...
             */
            accessToken: string;
            /**
             * @description Refresh JWT token
             * @example egrsa9876sgb9788sbhuisdfhoui...
             */
            refreshToken: string;
        };
        RefreshTokenSuccessDto: {
            /**
             * @description The authenticated user ID
             * @example 1
             */
            id: number;
            /**
             * @description Signed JWT access token
             * @example lsd234k5j5234k5lj1kj2h3g4341k2313kl2j2h4...
             */
            accessToken: string;
            /**
             * @description Signed REFRESH access token
             * @example lsd234k5j5234k5lj1kj2h3g4341k2313kl2j2h4...
             */
            refreshToken: string;
        };
        FindAllFriendshipsDto: {
            sentRequests: {
                userId: string;
                /** @enum {string} */
                status: "PENDING" | "ACCEPTED" | "DECLINED" | "BLOCKED";
                /** Format: date-time */
                createdAt: string;
            }[];
            receivedRequests: {
                userId: string;
                /** @enum {string} */
                status: "PENDING" | "ACCEPTED" | "DECLINED" | "BLOCKED";
                /** Format: date-time */
                createdAt: string;
            }[];
            acceptedFriends: {
                userId: string;
                /** @enum {string} */
                status: "PENDING" | "ACCEPTED" | "DECLINED" | "BLOCKED";
                /** Format: date-time */
                createdAt: string;
            }[];
        };
        GameSettingsDto: {
            /**
             * @description the max number of player to game in the game
             * @example 4
             */
            maxPlayer: number;
            /**
             * @description the max number of spectator to watch this game
             * @example 2
             */
            maxSpectator: number;
            /**
             * @description the format to play in this lobby
             * @example BEGINNER
             * @enum {string}
             */
            format: "BEGINNER" | "PRO" | "TURBO";
        };
        CreateLobbyDto: {
            /**
             * @description the catchphrase that would display when on the lobby list
             * @example warm up match welcom new player
             */
            catchPhrase?: Record<string, never>;
            /**
             * @description type of the game room
             * @example PUBLIC
             * @enum {string}
             */
            roomType: "PUBLIC" | "PRIVATE";
            /**
             * @description the password of the room if the roomType is set     to PUBLIC
             * @example 12345687
             */
            password?: Record<string, never>;
            gameSettings: components["schemas"]["GameSettingsDto"];
        };
        LobbyDto: {
            /**
             * @description the catchphrase that would display when on the lobby list
             * @example warm up match welcom new player
             */
            catchPhrase?: Record<string, never>;
            /**
             * @description type of the game room
             * @example PUBLIC
             * @enum {string}
             */
            roomType: "PUBLIC" | "PRIVATE";
            /**
             * @description the password of the room if the roomType is set     to PUBLIC
             * @example 12345687
             */
            password?: Record<string, never>;
            gameSettings: components["schemas"]["GameSettingsDto"];
            /**
             * @description the room identifier as       6 digits base-10 number randomly generated as string. User can use       this digit to quick join room
             * @example 020321
             */
            roomPinId: string;
            /**
             * Format: date-time
             * @description the time this lobby was created
             */
            createdAt: string;
            /** @description the user that created this lobby room */
            createdByUserId: string;
            /** @description the host user of the lobby room */
            hostUserId: string;
            /**
             * @description the current status of the lobby room
             * @example PLAYING
             * @enum {string}
             */
            roomStatus: "UNAVAILABLE" | "WAITING" | "PLAYING";
            /** @description the number of current player in the lobby room */
            currentPlayerCount: number;
            /** @description the number of current spectator in the lobby */
            currentSpectatorCount?: number;
        };
        JoinLobbyDto: {
            lobbyPinId: string;
            isSpectator: boolean;
            password?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    UserController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserDto"];
            };
        };
        responses: {
            /** @description User created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description validation failed. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedErrorDto"];
                };
            };
        };
    };
    UserController_getProfile: {
        parameters: {
            query?: {
                /** @description Lookup target profile by User ID (mutually exclusive with tagId) */
                id?: string;
                /** @description Lookup target profile by Tag/Handle (mutually exclusive with id) */
                tagId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully retrieved user profile data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetUserProfileDto"];
                };
            };
            /** @description Both `id` and `tagId` were provided simultaneously */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid JWT token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedErrorDto"];
                };
            };
        };
    };
    UserController_uploadProfilePic: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description Profile image file (JPG, JPEG, PNG, max 5MB)
                     */
                    file: string;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserController_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetUserProfileDto"];
                };
            };
        };
    };
    UserController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description successfully deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description invalid role, invalid Token, or expired Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedErrorDto"];
                };
            };
            /** @description invalid role? */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TitleController_getAllTitles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TitleDto"][];
                };
            };
        };
    };
    TitleController_getUserTitles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetUserTitleDto"][];
                };
            };
        };
    };
    TitleController_findTitle: {
        parameters: {
            query?: {
                /** @description the id of the title */
                titleId?: string;
                /** @description the name of the title */
                titleName?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TitleDto"];
                };
            };
            /** @description the titleId and titleName query cannot go together */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TitleController_createNewTitle: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateNewTitleZodDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TitleDto"];
                };
            };
        };
    };
    TitleController_giveUserTitle: {
        parameters: {
            query: {
                /** @description the target User to give the title */
                userId: string;
                /** @description the title you want to giv to the target user */
                titleId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserTitleDto"];
                };
            };
        };
    };
    TitleController_revokeUserTitle: {
        parameters: {
            query: {
                /** @description the target User to revoke the title */
                userId: string;
                /** @description the title you want to revoke from the target user */
                titleId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TitleController_updateTitle: {
        parameters: {
            query: {
                /** @description the title id of the title you want to change */
                titleId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTitleZodDto"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TitleController_deleteTitle: {
        parameters: {
            query: {
                /** @description the title id you want to delete */
                titleId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_authCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_registerUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description User login credentials */
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            /** @description Logged in successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginSuccessResponseDto"];
                };
            };
            /** @description Invalid email or password */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedErrorDto"];
                };
            };
        };
    };
    AuthController_refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description upon success would return new JWT token back */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshTokenSuccessDto"];
                };
            };
            /** @description invalid to expired refresh token. need to re-login for new generated one. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedErrorDto"];
                };
            };
        };
    };
    AuthController_signOut: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description successfully logged out */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description invalid access_token or expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedErrorDto"];
                };
            };
        };
    };
    AuthController_googleLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_googleCallback: {
        parameters: {
            query: {
                state: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_fortyTwoLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_fortyTwoCallback: {
        parameters: {
            query: {
                state: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ChatController_getAllUserRoom: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ChatController_dmUser: {
        parameters: {
            query: {
                targetUserId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    ChatController_getMessagesRoom: {
        parameters: {
            query: {
                chatRoomId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ChatController_createChatRoom: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ChatController_inviteToChatRoom: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ChatController_leaveTheChatRoom: {
        parameters: {
            query: {
                chatRoomId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ChatController_kickUserChatRoom: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FriendController_getAllFriends: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindAllFriendshipsDto"];
                };
            };
        };
    };
    FriendController_makeFriendRequest: {
        parameters: {
            query: {
                targetUserId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FriendController_acceptFriendRequest: {
        parameters: {
            query: {
                targetUserId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FriendController_rejectFriendRequest: {
        parameters: {
            query: {
                targetUserId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FriendController_blockUser: {
        parameters: {
            query: {
                targetUserId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LobbyController_createLobbyRoom: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLobbyDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LobbyDto"];
                };
            };
        };
    };
    LobbyController_joinLobbyRoom: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JoinLobbyDto"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LobbyController_leaveLobbyRoom: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LobbyController_getAllLobbyRoom: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LobbyController_updateGameSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
