
export const SHARED_STORAGE_PATH = '/transcend_storage';
export const STORAGE_URL_PATH = '/storage';

export const GLOBAL_LIMIT_FASTIFY_MULTIPART_FILESIZE_LIMIT = 1024 * 1024 * 50; // Hard limit for global use :50MB
export const GLOBAL_LIMIT_FASTIFY_MULTIPART_FILE_FIELD_MAX = 30;


// WEBSOCKET CONSTANT
export const WEBSOCKET_MAINGATEWAY_PRIVATE_USER_SOCKET_ROOM_PREFIX = "main_gateway_user_";


//########################################
// throttle Rate limit constants

export const THROTTLER_DEFAULT_LIMIT = 20;
export const THROTTLER_DEFAULT_TTL = 1000 * 10; // meaning 20 requests per 10 seconds

export const THROTTLER_AUTH_SIGNUP_LIMIT = 3;
export const THROTTLER_AUTH_SIGNUP_TTL = 1000 * 10;

export const THROTTLER_AUTH_LOGIN_LIMIT = 10;
export const THROTTLER_AUTH_LOGIN_TTL = 1000 * 60; // only 10 login request 

export const THROTTLER_AUTH_SIGNOUT_LIMIT = 10;
export const THROTTLER_AUTH_SIGNOUT_TTL = 1000 * 60; // per user

export const THROTTLER_USER_PROFILE_LIMIT = 10
export const THROTTLER_USER_PROFILE_TTL = 1000 * 10;

export const THROTTLER_USER_PROFILE_UPLOADPROFILEPIC_LIMIT = 3;
export const THROTTLER_USER_PROFILE_UPLOADPROFILEPIC_TTL = 1000 * 60;

export const THROTTLER_USER_PROFILE_UPDATE_LIMIT = 5;
export const THROTTLER_USER_PROFILE_UPDATE_TTL = 1000 * 60;

export const THROTTLER_FRIEND_CONTROLLER_LIMIT = 20;
export const THROTTLER_FRIEND_CONTROLLER_TTL = 1000 * 10;

export const THROTTLER_FRIEND_GET_LIMIT = 10;
export const THROTTLER_FRIEND_GET_TTL = 1000 * 10;

export const THROTTLER_FRIEND_REQUEST_LIMIT = 20;
export const THROTTLER_FRIEND_REQUEST_TTL = 1000 * 10;

export const THROTTLER_FRIEND_ACCEPT_LIMIT = 20;
export const THROTTLER_FRIEND_ACCEPT_TTL = 1000 * 10;

export const THROTTLER_FRIEND_REJECT_LIMIT = 20;
export const THROTTLER_FRIEND_REJECT_TTL = 1000 * 10;

export const THROTTLER_FRIEND_BLOCK_LIMIT = 20;
export const THROTTLER_FRIEND_BLOCK_TTL = 1000 * 10;

export const THROTTLER_CHAT_CONTROLLER_LIMIT = 20;
export const THROTTLER_CHAT_CONTROLLER_TTL = 1000 * 10;

export const THROTTLER_CHAT_GET_LIMIT = 20;
export const THROTTLER_CHAT_GET_TTL = 1000 * 10;

export const THROTTLER_CHAT_DM_LIMIT = 20;
export const THROTTLER_CHAT_DM_TTL = 1000 * 10;

export const THROTTLER_CHAT_MESSAGE_LIMIT = 20;
export const THROTTLER_CHAT_MESSAGE_TTL = 1000 * 10;

export const THROTTLER_CHAT_ROOM_CREATE_LIMIT = 20;
export const THROTTLER_CHAT_ROOM_CREATE_TTL = 1000 * 10;

export const THROTTLER_CHAT_ROOM_INVITE_LIMIT = 20;
export const THROTTLER_CHAT_ROOM_INVITE_TTL = 1000 * 10;

export const THROTTLER_CHAT_ROOM_LEAVE_LIMIT = 20;
export const THROTTLER_CHAT_ROOM_LEAVE_TTL = 1000 * 10;

//########################################

// CACHING EXPIRE TIME IS IN SECONDS
export const CACHING_USER_SERVICE_EXPIRE_TIME = 600;